# Makefile

all-clean: 
#all-clean: can2c tsp speech can2py
	cd ./can2c; make all-clean; cd ..
	cd ./can2comp; make all-clean; cd ..
	cd ./tsp; make all-clean; cd ..
	cd ./tspomp; make all-clean; cd ..
	cd ./speech; make all-clean; cd ..
	cd ./can2py; make all-clean; cd ..
	cd ./mspc; make all-clean; cd ..
	cd ./mspcomp; make all-clean; cd ..
